// Generated by gencpp from file snap_vision_msgs/Detector.msg
// DO NOT EDIT!


#ifndef SNAP_VISION_MSGS_MESSAGE_DETECTOR_H
#define SNAP_VISION_MSGS_MESSAGE_DETECTOR_H

#include <ros/service_traits.h>


#include <snap_vision_msgs/DetectorRequest.h>
#include <snap_vision_msgs/DetectorResponse.h>


namespace snap_vision_msgs
{

struct Detector
{

typedef DetectorRequest Request;
typedef DetectorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Detector
} // namespace snap_vision_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::snap_vision_msgs::Detector > {
  static const char* value()
  {
    return "828d12a4038cc11efb50c3781f23f856";
  }

  static const char* value(const ::snap_vision_msgs::Detector&) { return value(); }
};

template<>
struct DataType< ::snap_vision_msgs::Detector > {
  static const char* value()
  {
    return "snap_vision_msgs/Detector";
  }

  static const char* value(const ::snap_vision_msgs::Detector&) { return value(); }
};


// service_traits::MD5Sum< ::snap_vision_msgs::DetectorRequest> should match 
// service_traits::MD5Sum< ::snap_vision_msgs::Detector > 
template<>
struct MD5Sum< ::snap_vision_msgs::DetectorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::snap_vision_msgs::Detector >::value();
  }
  static const char* value(const ::snap_vision_msgs::DetectorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::snap_vision_msgs::DetectorRequest> should match 
// service_traits::DataType< ::snap_vision_msgs::Detector > 
template<>
struct DataType< ::snap_vision_msgs::DetectorRequest>
{
  static const char* value()
  {
    return DataType< ::snap_vision_msgs::Detector >::value();
  }
  static const char* value(const ::snap_vision_msgs::DetectorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::snap_vision_msgs::DetectorResponse> should match 
// service_traits::MD5Sum< ::snap_vision_msgs::Detector > 
template<>
struct MD5Sum< ::snap_vision_msgs::DetectorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::snap_vision_msgs::Detector >::value();
  }
  static const char* value(const ::snap_vision_msgs::DetectorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::snap_vision_msgs::DetectorResponse> should match 
// service_traits::DataType< ::snap_vision_msgs::Detector > 
template<>
struct DataType< ::snap_vision_msgs::DetectorResponse>
{
  static const char* value()
  {
    return DataType< ::snap_vision_msgs::Detector >::value();
  }
  static const char* value(const ::snap_vision_msgs::DetectorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SNAP_VISION_MSGS_MESSAGE_DETECTOR_H
