// Generated by gencpp from file snap_vision_msgs/LabeledImage.msg
// DO NOT EDIT!


#ifndef SNAP_VISION_MSGS_MESSAGE_LABELEDIMAGE_H
#define SNAP_VISION_MSGS_MESSAGE_LABELEDIMAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/Image.h>
#include <snap_vision_msgs/Detection.h>

namespace snap_vision_msgs
{
template <class ContainerAllocator>
struct LabeledImage_
{
  typedef LabeledImage_<ContainerAllocator> Type;

  LabeledImage_()
    : image()
    , detections()  {
    }
  LabeledImage_(const ContainerAllocator& _alloc)
    : image(_alloc)
    , detections(_alloc)  {
    }



   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _image_type;
  _image_type image;

   typedef std::vector< ::snap_vision_msgs::Detection_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::snap_vision_msgs::Detection_<ContainerAllocator> >::other >  _detections_type;
  _detections_type detections;




  typedef boost::shared_ptr< ::snap_vision_msgs::LabeledImage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::snap_vision_msgs::LabeledImage_<ContainerAllocator> const> ConstPtr;

}; // struct LabeledImage_

typedef ::snap_vision_msgs::LabeledImage_<std::allocator<void> > LabeledImage;

typedef boost::shared_ptr< ::snap_vision_msgs::LabeledImage > LabeledImagePtr;
typedef boost::shared_ptr< ::snap_vision_msgs::LabeledImage const> LabeledImageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::snap_vision_msgs::LabeledImage_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::snap_vision_msgs::LabeledImage_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace snap_vision_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'snap_vision_msgs': ['/home/genesis/code/ROS/catkin_ws/src/snap_vision_msgs/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::snap_vision_msgs::LabeledImage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::snap_vision_msgs::LabeledImage_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::snap_vision_msgs::LabeledImage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::snap_vision_msgs::LabeledImage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::snap_vision_msgs::LabeledImage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::snap_vision_msgs::LabeledImage_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::snap_vision_msgs::LabeledImage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "64cd3e5e867e8e8648a34ec6f85ed84c";
  }

  static const char* value(const ::snap_vision_msgs::LabeledImage_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x64cd3e5e867e8e86ULL;
  static const uint64_t static_value2 = 0x48a34ec6f85ed84cULL;
};

template<class ContainerAllocator>
struct DataType< ::snap_vision_msgs::LabeledImage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "snap_vision_msgs/LabeledImage";
  }

  static const char* value(const ::snap_vision_msgs::LabeledImage_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::snap_vision_msgs::LabeledImage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_msgs/Image image\n\
Detection[] detections\n\
\n\
================================================================================\n\
MSG: sensor_msgs/Image\n\
# This message contains an uncompressed image\n\
# (0, 0) is at top-left corner of image\n\
#\n\
\n\
Header header        # Header timestamp should be acquisition time of image\n\
                     # Header frame_id should be optical frame of camera\n\
                     # origin of frame should be optical center of cameara\n\
                     # +x should point to the right in the image\n\
                     # +y should point down in the image\n\
                     # +z should point into to plane of the image\n\
                     # If the frame_id here and the frame_id of the CameraInfo\n\
                     # message associated with the image conflict\n\
                     # the behavior is undefined\n\
\n\
uint32 height         # image height, that is, number of rows\n\
uint32 width          # image width, that is, number of columns\n\
\n\
# The legal values for encoding are in file src/image_encodings.cpp\n\
# If you want to standardize a new string format, join\n\
# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n\
\n\
string encoding       # Encoding of pixels -- channel meaning, ordering, size\n\
                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n\
\n\
uint8 is_bigendian    # is this data bigendian?\n\
uint32 step           # Full row length in bytes\n\
uint8[] data          # actual matrix data, size is (step * rows)\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: snap_vision_msgs/Detection\n\
string label\n\
BoundingBox bbox\n\
float32 confidence\n\
\n\
================================================================================\n\
MSG: snap_vision_msgs/BoundingBox\n\
float32 x\n\
float32 y\n\
float32 width\n\
float32 height\n\
";
  }

  static const char* value(const ::snap_vision_msgs::LabeledImage_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::snap_vision_msgs::LabeledImage_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.image);
      stream.next(m.detections);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct LabeledImage_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::snap_vision_msgs::LabeledImage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::snap_vision_msgs::LabeledImage_<ContainerAllocator>& v)
  {
    s << indent << "image: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.image);
    s << indent << "detections[]" << std::endl;
    for (size_t i = 0; i < v.detections.size(); ++i)
    {
      s << indent << "  detections[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::snap_vision_msgs::Detection_<ContainerAllocator> >::stream(s, indent + "    ", v.detections[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SNAP_VISION_MSGS_MESSAGE_LABELEDIMAGE_H
