// Generated by gencpp from file snap_vision_msgs/Models.msg
// DO NOT EDIT!


#ifndef SNAP_VISION_MSGS_MESSAGE_MODELS_H
#define SNAP_VISION_MSGS_MESSAGE_MODELS_H

#include <ros/service_traits.h>


#include <snap_vision_msgs/ModelsRequest.h>
#include <snap_vision_msgs/ModelsResponse.h>


namespace snap_vision_msgs
{

struct Models
{

typedef ModelsRequest Request;
typedef ModelsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Models
} // namespace snap_vision_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::snap_vision_msgs::Models > {
  static const char* value()
  {
    return "c85b5652a42141c2735c32a4f6235d0b";
  }

  static const char* value(const ::snap_vision_msgs::Models&) { return value(); }
};

template<>
struct DataType< ::snap_vision_msgs::Models > {
  static const char* value()
  {
    return "snap_vision_msgs/Models";
  }

  static const char* value(const ::snap_vision_msgs::Models&) { return value(); }
};


// service_traits::MD5Sum< ::snap_vision_msgs::ModelsRequest> should match 
// service_traits::MD5Sum< ::snap_vision_msgs::Models > 
template<>
struct MD5Sum< ::snap_vision_msgs::ModelsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::snap_vision_msgs::Models >::value();
  }
  static const char* value(const ::snap_vision_msgs::ModelsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::snap_vision_msgs::ModelsRequest> should match 
// service_traits::DataType< ::snap_vision_msgs::Models > 
template<>
struct DataType< ::snap_vision_msgs::ModelsRequest>
{
  static const char* value()
  {
    return DataType< ::snap_vision_msgs::Models >::value();
  }
  static const char* value(const ::snap_vision_msgs::ModelsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::snap_vision_msgs::ModelsResponse> should match 
// service_traits::MD5Sum< ::snap_vision_msgs::Models > 
template<>
struct MD5Sum< ::snap_vision_msgs::ModelsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::snap_vision_msgs::Models >::value();
  }
  static const char* value(const ::snap_vision_msgs::ModelsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::snap_vision_msgs::ModelsResponse> should match 
// service_traits::DataType< ::snap_vision_msgs::Models > 
template<>
struct DataType< ::snap_vision_msgs::ModelsResponse>
{
  static const char* value()
  {
    return DataType< ::snap_vision_msgs::Models >::value();
  }
  static const char* value(const ::snap_vision_msgs::ModelsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SNAP_VISION_MSGS_MESSAGE_MODELS_H
