// Generated by gencpp from file snap_vision_msgs/Params.msg
// DO NOT EDIT!


#ifndef SNAP_VISION_MSGS_MESSAGE_PARAMS_H
#define SNAP_VISION_MSGS_MESSAGE_PARAMS_H

#include <ros/service_traits.h>


#include <snap_vision_msgs/ParamsRequest.h>
#include <snap_vision_msgs/ParamsResponse.h>


namespace snap_vision_msgs
{

struct Params
{

typedef ParamsRequest Request;
typedef ParamsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Params
} // namespace snap_vision_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::snap_vision_msgs::Params > {
  static const char* value()
  {
    return "d31226ac986ba51011848f391809440f";
  }

  static const char* value(const ::snap_vision_msgs::Params&) { return value(); }
};

template<>
struct DataType< ::snap_vision_msgs::Params > {
  static const char* value()
  {
    return "snap_vision_msgs/Params";
  }

  static const char* value(const ::snap_vision_msgs::Params&) { return value(); }
};


// service_traits::MD5Sum< ::snap_vision_msgs::ParamsRequest> should match 
// service_traits::MD5Sum< ::snap_vision_msgs::Params > 
template<>
struct MD5Sum< ::snap_vision_msgs::ParamsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::snap_vision_msgs::Params >::value();
  }
  static const char* value(const ::snap_vision_msgs::ParamsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::snap_vision_msgs::ParamsRequest> should match 
// service_traits::DataType< ::snap_vision_msgs::Params > 
template<>
struct DataType< ::snap_vision_msgs::ParamsRequest>
{
  static const char* value()
  {
    return DataType< ::snap_vision_msgs::Params >::value();
  }
  static const char* value(const ::snap_vision_msgs::ParamsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::snap_vision_msgs::ParamsResponse> should match 
// service_traits::MD5Sum< ::snap_vision_msgs::Params > 
template<>
struct MD5Sum< ::snap_vision_msgs::ParamsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::snap_vision_msgs::Params >::value();
  }
  static const char* value(const ::snap_vision_msgs::ParamsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::snap_vision_msgs::ParamsResponse> should match 
// service_traits::DataType< ::snap_vision_msgs::Params > 
template<>
struct DataType< ::snap_vision_msgs::ParamsResponse>
{
  static const char* value()
  {
    return DataType< ::snap_vision_msgs::Params >::value();
  }
  static const char* value(const ::snap_vision_msgs::ParamsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SNAP_VISION_MSGS_MESSAGE_PARAMS_H
