// Generated by gencpp from file snap_vision_msgs/StreamRequest.msg
// DO NOT EDIT!


#ifndef SNAP_VISION_MSGS_MESSAGE_STREAMREQUEST_H
#define SNAP_VISION_MSGS_MESSAGE_STREAMREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace snap_vision_msgs
{
template <class ContainerAllocator>
struct StreamRequest_
{
  typedef StreamRequest_<ContainerAllocator> Type;

  StreamRequest_()
    : topic_name()
    , queue_size(0)  {
    }
  StreamRequest_(const ContainerAllocator& _alloc)
    : topic_name(_alloc)
    , queue_size(0)  {
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _topic_name_type;
  _topic_name_type topic_name;

   typedef uint32_t _queue_size_type;
  _queue_size_type queue_size;




  typedef boost::shared_ptr< ::snap_vision_msgs::StreamRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::snap_vision_msgs::StreamRequest_<ContainerAllocator> const> ConstPtr;

}; // struct StreamRequest_

typedef ::snap_vision_msgs::StreamRequest_<std::allocator<void> > StreamRequest;

typedef boost::shared_ptr< ::snap_vision_msgs::StreamRequest > StreamRequestPtr;
typedef boost::shared_ptr< ::snap_vision_msgs::StreamRequest const> StreamRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::snap_vision_msgs::StreamRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::snap_vision_msgs::StreamRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace snap_vision_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'snap_vision_msgs': ['/home/genesis/code/ROS/catkin_ws/src/snap_vision_msgs/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::snap_vision_msgs::StreamRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::snap_vision_msgs::StreamRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::snap_vision_msgs::StreamRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::snap_vision_msgs::StreamRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::snap_vision_msgs::StreamRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::snap_vision_msgs::StreamRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::snap_vision_msgs::StreamRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f887ee8b01cf70d57a7149ed7630d92e";
  }

  static const char* value(const ::snap_vision_msgs::StreamRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf887ee8b01cf70d5ULL;
  static const uint64_t static_value2 = 0x7a7149ed7630d92eULL;
};

template<class ContainerAllocator>
struct DataType< ::snap_vision_msgs::StreamRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "snap_vision_msgs/StreamRequest";
  }

  static const char* value(const ::snap_vision_msgs::StreamRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::snap_vision_msgs::StreamRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
string topic_name\n\
uint32 queue_size\n\
\n\
";
  }

  static const char* value(const ::snap_vision_msgs::StreamRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::snap_vision_msgs::StreamRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.topic_name);
      stream.next(m.queue_size);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct StreamRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::snap_vision_msgs::StreamRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::snap_vision_msgs::StreamRequest_<ContainerAllocator>& v)
  {
    s << indent << "topic_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.topic_name);
    s << indent << "queue_size: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.queue_size);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SNAP_VISION_MSGS_MESSAGE_STREAMREQUEST_H
