// Generated by gencpp from file snap_vision_msgs/Stream.msg
// DO NOT EDIT!


#ifndef SNAP_VISION_MSGS_MESSAGE_STREAM_H
#define SNAP_VISION_MSGS_MESSAGE_STREAM_H

#include <ros/service_traits.h>


#include <snap_vision_msgs/StreamRequest.h>
#include <snap_vision_msgs/StreamResponse.h>


namespace snap_vision_msgs
{

struct Stream
{

typedef StreamRequest Request;
typedef StreamResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Stream
} // namespace snap_vision_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::snap_vision_msgs::Stream > {
  static const char* value()
  {
    return "0f745686c18f31265b0311f085eb5f84";
  }

  static const char* value(const ::snap_vision_msgs::Stream&) { return value(); }
};

template<>
struct DataType< ::snap_vision_msgs::Stream > {
  static const char* value()
  {
    return "snap_vision_msgs/Stream";
  }

  static const char* value(const ::snap_vision_msgs::Stream&) { return value(); }
};


// service_traits::MD5Sum< ::snap_vision_msgs::StreamRequest> should match 
// service_traits::MD5Sum< ::snap_vision_msgs::Stream > 
template<>
struct MD5Sum< ::snap_vision_msgs::StreamRequest>
{
  static const char* value()
  {
    return MD5Sum< ::snap_vision_msgs::Stream >::value();
  }
  static const char* value(const ::snap_vision_msgs::StreamRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::snap_vision_msgs::StreamRequest> should match 
// service_traits::DataType< ::snap_vision_msgs::Stream > 
template<>
struct DataType< ::snap_vision_msgs::StreamRequest>
{
  static const char* value()
  {
    return DataType< ::snap_vision_msgs::Stream >::value();
  }
  static const char* value(const ::snap_vision_msgs::StreamRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::snap_vision_msgs::StreamResponse> should match 
// service_traits::MD5Sum< ::snap_vision_msgs::Stream > 
template<>
struct MD5Sum< ::snap_vision_msgs::StreamResponse>
{
  static const char* value()
  {
    return MD5Sum< ::snap_vision_msgs::Stream >::value();
  }
  static const char* value(const ::snap_vision_msgs::StreamResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::snap_vision_msgs::StreamResponse> should match 
// service_traits::DataType< ::snap_vision_msgs::Stream > 
template<>
struct DataType< ::snap_vision_msgs::StreamResponse>
{
  static const char* value()
  {
    return DataType< ::snap_vision_msgs::Stream >::value();
  }
  static const char* value(const ::snap_vision_msgs::StreamResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SNAP_VISION_MSGS_MESSAGE_STREAM_H
