(cl:defpackage snap_vision_msgs-srv
  (:use )
  (:export
   "PARAMS"
   "<PARAMS-REQUEST>"
   "PARAMS-REQUEST"
   "<PARAMS-RESPONSE>"
   "PARAMS-RESPONSE"
   "DETECTOR"
   "<DETECTOR-REQUEST>"
   "DETECTOR-REQUEST"
   "<DETECTOR-RESPONSE>"
   "DETECTOR-RESPONSE"
   "MODELS"
   "<MODELS-REQUEST>"
   "MODELS-REQUEST"
   "<MODELS-RESPONSE>"
   "MODELS-RESPONSE"
   "STREAM"
   "<STREAM-REQUEST>"
   "STREAM-REQUEST"
   "<STREAM-RESPONSE>"
   "STREAM-RESPONSE"
  ))

